### ISSUE TITLE
YAML format for project metada

### ISSUE THREAD

**Issue by kugtong33** [Lintad/caddisfly#1]
The project should have a `database.yml` which contains the following information.

- Project
- Hostname
- Port
- User
- Database
- Schema (currently supports PostgreSQL)

`database.yml` example (for PostgreSQL):

```yml
- project: pgsql
- host: localhost
- port: 5432
- user: postgres
- database: postgres
- schema:
  - schema1
  - schema2
  - schema3
```
